INSERT INTO TODOLIST (ID) VALUES ( 1 );
INSERT INTO TODO (ID, TEXT, COMPLETED, TODO_LIST_ID) VALUES ( 1, 'Existing Todo 1', 0, 1 );
INSERT INTO TODO (ID, TEXT, COMPLETED, TODO_LIST_ID) VALUES ( 2, 'Existing Todo 2', 0, 1 );
