INSERT INTO TODOLIST (ID) VALUES ( 1 );
INSERT INTO TODO (ID, TEXT, COMPLETED, TODO_LIST_ID) VALUES ( 1, 'Existing Todo 1', 0, 1 );
INSERT INTO TODO (ID, TEXT, COMPLETED, TODO_LIST_ID) VALUES ( 2, 'Existing Todo 2', 0, 1 );

INSERT INTO TODOLIST (ID) VALUES ( 2 );
INSERT INTO TODO (ID, TEXT, COMPLETED, TODO_LIST_ID) VALUES ( 3, 'Existing Todo 3', 0, 2 );
INSERT INTO TODO (ID, TEXT, COMPLETED, TODO_LIST_ID) VALUES ( 4, 'Existing Todo 4', 0, 2 );
